### PR TITLE
Reorganize unit/integration tests and deduplicate

### PR DESCRIPTION
**Pull request by 0xAlcibiades**
Reorganize unit tests to maximize compatibility with audit threat model to easily add needed additional cases. Additionally, remove duplicate coverage, complete refactor to separate file organization.

Screen Shot 2022-12-22 at 03 32 28

We can now more easily extend fuzz coverage, and add a sweeping integration test if we are inclined, though fuzzing and invariant testing may preclude.

### CODE REVIEW

**Comment by 0xAlcibiades** [comment]
Screen Shot 2022-12-22 at 03 15 19

**Comment by 0xAlcibiades** [comment]
The 2 logic branches not covered by the unit tests weren't covered by the whole test suite to begin with, would be great to track them down @neodaoist.

**Comment by 0xAlcibiades** [comment]
> The 2 logic branches not covered by the unit tests weren't covered by the whole test suite to begin with, would be great to track them down @neodaoist.

Might be unreachable code, actually.

**Comment by Flip-Liquid** [comment]
@0xAlcibiades want to back out the changes to the actor files? Those will conflict with the changes I'm making, and it looks like they're not substantive changes

**Pull request merged**
