### PR TITLE
impl unexercised list of buckets for write & assign exercise

### PR DESCRIPTION
**Pull request by Flip-Liquid**
**Raw new gas report:**
image

**Raw Original**
image

**Comparison**
image

### CODE REVIEW

**Review by neodaoist — COMMENTED** [review]
One idea to try and hit that worst case is add something like to foundry.toml 

[fuzz]
runs = 10000

**Comment by 0xAlcibiades** [comment]
@Flip-Liquid we need to resolve merge conflicts here.

**Comment by neodaoist** [comment]
Some open ideas/Qs after pairing w/ Flip:

- Priority queue? What if we store amount of unexercised options per bucket, not just boolean, then we could prioritize assigning from buckets that have the most chance of fulfilling the assign. (Does this hurt fair assignment, by biasing towards days with higher amounts written?)
- Is day the right time unit for bucketing?
- Naming, how about
  - Claim
  - ClaimBucket
  - ClaimBucketIndex

**Review by 0xAlcibiades — APPROVED** [review]

**Comment by 0xAlcibiades** [comment]
This addresses the growth of `O` sufficiently to make the protocol not game-able by writers.

**Pull request merged**
