### PR TITLE
Rename Underlying to Position — why overload `Underlying`?

### PR DESCRIPTION
**Pull request by neodaoist**

### CODE REVIEW

**Comment by 0xAlcibiades** [comment]
@neodaoist This needs conflicts resolved.

**Review by 0xAlcibiades — APPROVED** [review]
This looks good once the merge conflict is resolved.

**Comment by neodaoist** [comment]
> This looks good once the merge conflict is resolved.

Addressed merge conflicts and some lite cleanup. Probably worth your perusing the diff before merging but should be GTG

**Comment by neodaoist** [comment]
More updates — took a pass on Exercise Assignment NatSpec and added subcategories to private functions.

**Pull request merged**
